# Site settings
title: jayinlab
description: private database
theme: jekyll-theme-slate

# Post
permalink: none

# Collections
collections:
  wiki:
    output: true
    permalink: /:collection/:path/
  media:
    output: true
    permalink: /:collection/:path/
    
# Service
google_analytics: