# Site settings
title: jayinlab
description: private wiki
theme: jekyll-theme-slate

# Collections
collections:
  wiki:
    output: true
    permalink: /:collection/:path/

# Service
google_analytics: